(TeX-add-style-hook "cpp"
 (lambda ()
    (LaTeX-add-bibliographies
     "resumen")
    (LaTeX-add-environments
     "lemma"
     "prop"
     "coro"
     "teo")
    (LaTeX-add-labels
     "fig:alphainduction"
     "fig:alpha"
     "pequiv"
     "sec:parallel"
     "fig:parallel"
     "prightalpha"
     "pleftalpha"
     "pfresh"
     "lamelim"
     "betaelim")
    (TeX-add-symbols
     "cL"
     "alp"
     "lam"
     "alpsym"
     "choice"
     "p"
     "ninb"
     "betar"
     "conc")
    (TeX-run-style-hooks
     "amsthm"
     "amssymb"
     "bussproofs"
     "hyperref"
     "amsmath"
     ""
     "latex2e"
     "sigplanconf10"
     "sigplanconf"
     "10pt"
     "preprint")))

